In [16]:
import numpy as np
from keras.callbacks import EarlyStopping
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Flatten
from keras.layers import Conv2D
from keras.optimizers import Adam
from keras.layers.pooling import MaxPooling2D
from keras.utils import np_utils

In [17]:
num_classes = 5
epochs = 200
data_augmentation = False
num_predictions = 30
batch_size = 128

In [30]:
model = Sequential()

model.add(Conv2D(32,(3, 3), activation='relu', input_shape=(64, 64, 3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(5, activation='softmax'))

In [31]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 62, 62, 32)        896       
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 60, 60, 64)        18496     
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 30, 30, 64)        0         
_________________________________________________________________
dropout_6 (Dropout)          (None, 30, 30, 64)        0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 28, 28, 128)       73856     
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 12, 12, 128)       147584    
__________

In [32]:
opt  = Adam(lr=0.0001, decay=1e-6)

In [33]:
model.compile(loss='categorical_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])

In [34]:
from keras.preprocessing.image import ImageDataGenerator

In [35]:
train_datagen = ImageDataGenerator(rescale = 1./255, 
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

In [36]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [37]:
training_set = train_datagen.flow_from_directory('dataset/training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32)

Found 3121 images belonging to 5 classes.


In [38]:
test_set = test_datagen.flow_from_directory('dataset/test_set',
                                            target_size = (64, 64),
                                            batch_size = 32)

Found 832 images belonging to 5 classes.


In [40]:
model.fit_generator(training_set,
                         samples_per_epoch = 3121,
                         nb_epoch = 1, 
                         validation_data = test_set,
                         nb_val_samples = 832 )

/home/shuja1497/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., validation_data=<keras.pre..., steps_per_epoch=97, epochs=1, validation_steps=832)`
  """


Epoch 1/1
97/97 [==============================] - 1597s - loss: 0.4004 - acc: 0.8674 - val_loss: 0.2678 - val_acc: 0.9448


In [41]:
from keras.models import load_model

In [42]:
model.save('dundun.h5')

In [43]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 62, 62, 32)        896       
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 60, 60, 64)        18496     
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 30, 30, 64)        0         
_________________________________________________________________
dropout_6 (Dropout)          (None, 30, 30, 64)        0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 28, 28, 128)       73856     
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 14, 14, 128)       0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 12, 12, 128)       147584    
__________

In [44]:
from keras.models import load_model
model= load_model('dundun.h5')

In [50]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('l1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)

In [51]:
print result

[[ 0.  0.  0.  1.  0.]]


In [52]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('l2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)

In [53]:
print result

[[ 0.  0.  0.  1.  0.]]


In [56]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('l3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)

In [57]:
print result

[[ 0.  1.  0.  0.  0.]]


In [58]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)

In [59]:
print result

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    9.37634407e-37]]


In [60]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)

In [61]:
print result 

[[  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.19130955e-29
    0.00000000e+00]]


In [62]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [63]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [64]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [65]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [66]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b4.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [68]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle46.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [69]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle314.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [70]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle140.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [71]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bag53.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [72]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bag93.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [73]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair1.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [75]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair250.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [76]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair397.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [77]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [78]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [79]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [80]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   1.67713723e-18
    0.00000000e+00]]


In [81]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [82]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [83]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt4.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [84]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt5.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.          0.99884242  0.          0.00115766  0.        ]]


In [85]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt6.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [86]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt7.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [87]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt8.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [88]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bt9.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[  0.00000000e+00   1.00000000e+00   0.00000000e+00   1.22612231e-09
    0.00000000e+00]]


In [89]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [90]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  0.  1.]]


In [91]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.          0.          0.90634793  0.          0.09365209]]


In [92]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b4.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [93]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b5.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [94]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b6.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [95]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b7.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [96]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('b8.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [97]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [98]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [99]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [100]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('m4.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [101]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c1.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [102]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c2.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [103]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c3.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [104]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c4.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [105]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c5.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [106]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c6.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  0.  1.  0.]]


In [107]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('c7.jpg', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [112]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair1.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [113]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair37.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [114]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair256.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [115]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('chair391.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  0.  1.  0.  0.]]


In [116]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle1.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [117]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle154.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [118]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle266.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [119]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bottle541.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 0.  1.  0.  0.  0.]]


In [120]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bag1.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [121]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bag10015.png' , target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]


In [123]:
from keras.preprocessing import image as image_utils
test_image = image_utils.load_img('bag40.png', target_size=(64, 64))
test_image = image_utils.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = model.predict_on_batch(test_image)
print result

[[ 1.  0.  0.  0.  0.]]
